name: My First Pipeline

on: push

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: echo "Building the project..."
      - run: echo "Running tests..."
      - run: exit 1
      - run: echo "This line should never run"