name: My First Pipeline

on: push

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: echo "Building the project..."
      - run: echo "Running tests..."
      - run: exit 1
    

  deploy:
    needs: build-and-test
    runs-on: ubuntu-latest
    steps:
      - run: echo "Deploying to production..."
      - run: echo "Deployment successful! App is live."